:PROPERTIES:
:ID:       4e19a1d3-1d5e-4324-bab0-a1c872bd87c8
:END:
#+title: zenlv-a-synopsis-of-sorts

#+BEGIN_CENTER
link: https://zenlasvegas.com/100-a-synopsis-of-sorts/
#+END_CENTER


#+BEGIN_VERSE
Most of the blogs have been directing techniques and meditation practices "user friendly format for 21st Century life"

Ideas of breathing techniques, Ānāpānasati Sutta [[[https://en.wikipedia.org/wiki/%C4%80n%C4%81p%C4%81nasati_Sutta][wiki]]] ("purported to be the meditation method of Buddha himself")
Naikan meditation [[[https://en.wikipedia.org/wiki/Naikan][wiki]]], have been shared despite difficulty in distilling the Pali texts to their skeletal teachings.

Ideas of Focus and discipline brought about by the Japanese "do" or, in English trans., "way" (as in "kendo or kyudo").
+ "zen enters through the body"
+ "zen is mind-sitting, not body-sitting"
+ tranquility and wisdom
tranquility may be acheived by "simultaneous calming of the body sensation and emotions generated by a wandering thought process"
wisdom is embodying "serenity and quiescence in turn affects our physical bodily deportment allowing for correct function and relationship to life's various and every changing social involvement and responnsibilities"

argues a "certain dispassion that requires cultivation" is necessary.

visibility and transparency of self-identity grant a greater ease to the passing emphemera of phenomena. holding on to the 'thing' "results in creating a dichotomy and chasm that is pure fiction"

zen ancestors talk about, "all buddhas and sentient beings are simply the One Mind -- no beginning, no end"
Heart Sutra [[[https://en.wikipedia.org/wiki/Heart_Sutra][wiki]]]

mental constructs are sought to be externally vaidated and reinforced, but it is experience. "What are you doing right now?"
"cognitive attempts at using the mind to grasp at what is ever changing phenomena is a dead end" mind does not fix the mind

slow down conceptual thought, lessen anxiety, allow peace and tranquility through the techniques shared above

#+END_VERSE
